# docker-compose.yml
version: '3.8'
services:
  application:
    build: .
    ports:
      - '5000:5000'
    environment:
      NEO4J_HOST: database
    env_file:
      - 'docker_env'
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy      
volumes:
  dbdata: